version: 2
jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: katalon-execute.sh -browserType="Web Service" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/View and create user"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report